openapi: 3.0.3
info:
  title: GymLog API
  description: API para la aplicación GymLog
  version: 1.0.0
tags:
  - name: Auth
    description: Autenticación y gestión de usuarios
  - name: Tenants
    description: Gestión de clientes/gimnasios (multi-tenant)
  - name: Exercises
    description: Operaciones sobre el banco de ejercicios
  - name: Routines
    description: Gestión de las rutinas de los usuarios
  - name: Workout Sessions
    description: Registro de sesiones de entrenamiento

paths:
  # Endpoints de Autenticación
  /api/v1/auth/social-login:
    post:
      tags:
        - Auth
      operationId: socialLogin
      summary: Login con proveedores sociales
      description: Valida un token social y devuelve un JWT de la aplicación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialLoginDTO'
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDTO'
        '401':
          description: Token social inválido
        '500':
          description: Error del servidor

  /api/v1/auth/me:
    get:
      tags:
        - Auth
      operationId: getCurrentUser
      summary: Obtener usuario actual
      description: Obtiene la información del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Información del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '401':
          description: Token JWT inválido

  # Endpoints de Gestión de Tenants
  /api/v1/tenants:
    post:
      tags:
        - Tenants
      operationId: createTenant
      summary: Crear nuevo cliente/gimnasio
      description: Crea un nuevo tenant con su esquema de BD y ejecuta migraciones iniciales
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantDTO'
      responses:
        '201':
          description: Tenant creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantDTO'
        '400':
          description: Datos de entrada inválidos
        '401':
          description: No autorizado
        '403':
          description: Sin permisos para crear tenants
        '500':
          description: Error del servidor
    get:
      tags:
        - Tenants
      operationId: getAllTenants
      summary: Listar todos los clientes/gimnasios
      description: Obtiene la lista de todos los tenants registrados (solo super admins)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tenants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TenantDTO'
        '401':
          description: No autorizado
        '403':
          description: Sin permisos para listar tenants

  /api/v1/tenants/{id}:
    get:
      tags:
        - Tenants
      operationId: getTenantById
      summary: Obtener información de un tenant
      description: Obtiene información detallada de un tenant específico
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID del tenant
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Información del tenant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantDTO'
        '401':
          description: No autorizado
        '403':
          description: Sin permisos para acceder a este tenant
        '404':
          description: Tenant no encontrado

  /api/v1/exercises:
    get:
      tags:
        - Exercises
      summary: Buscar ejercicios
      description: Busca ejercicios en el banco global, con filtros opcionales.
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Filtrar por nombre del ejercicio
          schema:
            type: string
        - name: targetMuscleGroup
          in: query
          description: Filtrar por grupo muscular
          schema:
            type: string
      responses:
        '200':
          description: Lista de ejercicios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExerciseDTO'
    post:
      tags:
        - Exercises
      summary: Crear un nuevo ejercicio
      description: Añade un nuevo ejercicio al banco, que puede ser público o privado.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExerciseDTO'
      responses:
        '201':
          description: Ejercicio creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseDTO'

  /api/v1/exercises/{id}:
    put:
      tags:
        - Exercises
      summary: Actualizar un ejercicio
      description: Actualiza un ejercicio existente que haya sido creado por el usuario.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExerciseDTO'
      responses:
        '200':
          description: Ejercicio actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseDTO'

  /api/v1/routines:
    get:
      tags:
        - Routines
      summary: Obtener todas las rutinas del usuario
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de rutinas del usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoutineDTO'
    post:
      tags:
        - Routines
      summary: Crear una nueva rutina
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoutineDTO'
      responses:
        '201':
          description: Rutina creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutineDTO'

  /api/v1/routines/{id}:
    get:
      tags:
        - Routines
      summary: Obtener el detalle de una rutina
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Detalle de la rutina
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutineDetailDTO'
    put:
      tags:
        - Routines
      summary: Actualizar una rutina
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoutineDTO'
      responses:
        '200':
          description: Rutina actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutineDTO'
    delete:
      tags:
        - Routines
      summary: Eliminar una rutina
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Rutina eliminada

  /api/v1/workout-sessions:
    post:
      tags:
        - Workout Sessions
      summary: Iniciar una nueva sesión de entrenamiento
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkoutSessionDTO'
      responses:
        '201':
          description: Sesión de entrenamiento iniciada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutSessionDTO'

  /api/v1/workout-sessions/{sessionId}/logs:
    post:
      tags:
        - Workout Sessions
      summary: Registrar el rendimiento de un ejercicio
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExerciseLogDTO'
      responses:
        '201':
          description: Registro de ejercicio creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseLogDTO'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # DTOs de Autenticación
    SocialLoginDTO:
      type: object
      required:
        - provider
        - token
      properties:
        provider:
          type: string
          enum: [google, apple, facebook]
        token:
          type: string
          description: Token de identidad del proveedor social

    AuthResponseDTO:
      type: object
      required:
        - jwt
        - user
      properties:
        jwt:
          type: string
          description: JWT de la aplicación GymLog
        user:
          $ref: '#/components/schemas/UserDTO'

    UserDTO:
      type: object
      required:
        - id
        - name
        - email
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        profileImageUrl:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ExerciseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        videoUrl:
          type: string
        targetMuscleGroup:
          type: string
        isPublic:
          type: boolean

    CreateExerciseDTO:
      type: object
      required:
        - name
        - targetMuscleGroup
      properties:
        name:
          type: string
        description:
          type: string
        videoUrl:
          type: string
        targetMuscleGroup:
          type: string
        isPublic:
          type: boolean
          default: true

    UpdateExerciseDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        videoUrl:
          type: string
        targetMuscleGroup:
          type: string
        isPublic:
          type: boolean

    RoutineDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        isActive:
          type: boolean

    CreateRoutineDTO:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        isActive:
          type: boolean
          default: false

    UpdateRoutineDTO:
      type: object
      properties:
        name:
          type: string
        isActive:
          type: boolean

    RoutineDetailDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        isActive:
          type: boolean
        days:
          type: array
          items:
            $ref: '#/components/schemas/RoutineDayDTO'

    RoutineDayDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        orderNum:
          type: integer
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/RoutineExerciseDTO'

    RoutineExerciseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        exerciseId:
          type: string
          format: uuid
        orderNum:
          type: integer
        isActive:
          type: boolean
        notes:
          type: string

    WorkoutSessionDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        routineDayId:
          type: string
          format: uuid
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        notes:
          type: string

    CreateWorkoutSessionDTO:
      type: object
      properties:
        routineDayId:
          type: string
          format: uuid
        notes:
          type: string

    CreateExerciseLogDTO:
      type: object
      required:
        - routineExerciseId
        - setsCompleted
        - repsAchieved
        - weightKg
      properties:
        routineExerciseId:
          type: string
          format: uuid
        setsCompleted:
          type: integer
        repsAchieved:
          type: string
        weightKg:
          type: number
        notes:
          type: string

    ExerciseLogDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        routineExerciseId:
          type: string
          format: uuid
        setsCompleted:
          type: integer
        repsAchieved:
          type: string
        weightKg:
          type: number
        notes:
          type: string
        recordedAt:
          type: string
          format: date-time

    # Schemas para Multi-Tenancy
    CreateTenantDTO:
      type: object
      required:
        - name
        - email
        - plan
      properties:
        name:
          type: string
          description: Nombre del gimnasio/cliente
          example: "Gimnasio Central"
        email:
          type: string
          format: email
          description: Email del administrador del gimnasio
          example: "admin@gimnasiocentral.com"
        plan:
          type: string
          enum: [basic, premium, enterprise]
          description: Plan de suscripción del gimnasio
          example: "premium"
        description:
          type: string
          description: Descripción opcional del gimnasio
          example: "Gimnasio especializado en fitness y musculación"
        address:
          type: string
          description: Dirección física del gimnasio
          example: "Calle Principal 123, Madrid"
        phone:
          type: string
          description: Teléfono de contacto
          example: "+34 91 123 45 67"

    TenantDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID único del tenant
        name:
          type: string
          description: Nombre del gimnasio/cliente
        email:
          type: string
          format: email
          description: Email del administrador
        plan:
          type: string
          enum: [basic, premium, enterprise]
          description: Plan de suscripción
        description:
          type: string
          description: Descripción del gimnasio
        address:
          type: string
          description: Dirección física
        phone:
          type: string
          description: Teléfono de contacto
        schemaName:
          type: string
          description: Nombre del esquema de BD asignado
          example: "gym_001"
        isActive:
          type: boolean
          description: Si el tenant está activo
          default: true
        createdAt:
          type: string
          format: date-time
          description: Fecha de creación
        updatedAt:
          type: string
          format: date-time
          description: Fecha de última actualización
