spring:
  profiles:
    active: dev
  application:
    name: gymlog
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gymlog
    username: user
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,loggers"
      base-path: /management
  endpoint:
    health:
      show-details: always

# Configuración de seguridad personalizada y robusta
gymlog:
  security:
    jwt-key: "una-clave-secreta-muy-larga-y-segura-para-firmar-tokens-jwt-en-desarrollo"
    social:
      google:
        # Lista de client IDs válidos para Google (configurar según tu app)
        client-ids:
          - "tu-google-client-id.apps.googleusercontent.com"
      facebook:
        # App ID y App Secret de Facebook (opcional para validación adicional)
        app-id: "tu-facebook-app-id"
        app-secret: "tu-facebook-app-secret"
      apple:
        # Team ID y Bundle ID de Apple (para validación completa en producción)
        team-id: "tu-apple-team-id"
        bundle-id: "com.tu-app.bundle-id"
